name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  m324-lint-format-test:
    name: Lint, Format and Test (M324)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint
